services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Nginx expose le port 80, mais on l'expose sur 3000 côté host
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
